name: Release 
 
on:
  workflow_dispatch:
    inputs:
      libsToRelease:
        description: 'Libraries to release'
        required: true
        default: 'PlugUtopia.Plugin.Template'
        type: choice
        options:
        - PlugUtopia.Plugin.Template
        # - Common.Plugin.Utils
      preRelease:
        description: 'pre-release (def: false)'
        required: false
        default: false
        type: boolean     

jobs:
  filter:
    outputs:
      changed: ${{ steps.changes.outputs.changed }}  
    name: Detect Path
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
           filters: |
              changed:
                - 'src/**'
  release:
    needs: filter
    if: ${{ (needs.filter.outputs.changed == 'true' && github.event_name == 'push') || (inputs.libsToRelease == 'all') ||  (inputs.libsToRelease == 'PlugUtopia.Plugin.Template')}}
    uses: pietroserrano/plugutopia/.github/workflows/nuget.yml@main
    with:
      NET_VERSION: '9.x'
      PROJECT_DIRECTORY_NAME: src/working
      PROJECT_FILENAME: PlugUtopia.Plugin.Templates.csproj
      PREFIX_TAG: PlugUtopia.Plugin.Templates
      RELEASE: PlugUtopia.Plugin.Templates
      IS_PRE_RELEASE: ${{ contains(inputs.preRelease, 'true') }}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NUGET_SOURCE: https://api.nuget.org/v3/index.json
 
